services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  KonradMichalik\Typo3BackendThemes\:
    resource: '../Classes/*'

  KonradMichalik\Typo3BackendThemes\Service\ThemeService:
    public: true

  KonradMichalik\Typo3BackendThemes\Backend\Form\ItemsProcFunc\ThemeItemsProcFunc:
    public: true

  KonradMichalik\Typo3BackendThemes\Hook\DataHandlerHook:
    public: true
